export default {
  done: 'Done',
  splash: {
    welcome: 'WELCOME TO',
    speedyFax: 'SPEEDY FAX APP',
    start: 'START FAXING',
  },
  bottomTab: {
    NewFax: 'New Fax',
    history: 'History',
    setting: 'Setting',
  },
  bottomTabHeader: {
    newFax: 'New Fax',
    history: 'Fax History',
    setting: 'Setting',
  },
  newFaxStack: {
    clear: 'Clear',
    next: 'Next',
  },
  newFaxScreen: {
    number: 'Enter fax number',
    sendFaxes: 'Send Fax for FREE!',
    subscribe: 'Subscribe & Fax Unlimited',
    sendTo: 'Step 1. Choose Recepient',
    add: 'Add',
    free: ' “Free” ',
    coverPage: 'Cover Page',
    addFreeCover: 'Add Free Cover Page',
    addDocument: 'Add Document\nImage',
    freed: 'Free',
    addDoc: 'Step 2. Choose document',
  },
  history: {
    delivered: 'Delivered',
    page: ' Page ',
    faxSent: 'Fax Sent',
    no: 'no send faxes yet!',
    notDelivered: 'Not Delivered',
    seeWay: 'See why',
    contactSupport: 'Contact support',
  },
  setting: {
    support: 'SUPPORT : - ',
    grettings:
      'Greetings form Speedy fax app.\n Ask us anything,\n and/or share your feedback',
    clickOperator:
      'Click on the operator icon below and we will respond < 2 minutes',
    chat: 'LIVE CHAT',
    copyright: 'Copyright 2024@ Geodelic Inc. All Rights Reserved.',
    features: 'For More Features',
    signin: 'Sign in ',
    with: 'with',
    type: 'Apple Account' /* 'Mobile, Google, Apple or Email' */,
    availableCredits: 'Available Credits',
    fax1: '10 credits = 1 fax page',
    credits: ' Credits',
    getUnlimited: 'Get Unlimited Faxes',
    unlimited: 'Unlimited Faxes',
    subscription: 'SUBSCRIPTION',
    information: 'General Information',
    email: 'Email',
    phoneNumber: 'Phone Number',
    name: 'Your Name',
    delete: 'Delete',
    membership: 'MEMBERSHIP',
    faxAvailable: 'Sending Faxes is available now',
    senderInformation: 'Sender information',
    cancelSubscription: 'Cancel Subscription',
    active: 'Active',
    deliveryTracking: 'Fax Delivery Tracking',
    noAds: 'No Ads',
    enablePushNotification: 'Enable Push Notification',
    changePassword: 'Change Password',
    application: 'APPLICATION',
    contactSupport: 'Contact Support',
    tellFriend: 'Tell a friend',
    faq: 'FAQ',
    recoverCredits: 'Recover Your Credits',
    promoCode: 'Enter Promo Code',
  },
  login: {
    login: 'Sign In',
    number: 'Enter mobile number',
    signInWithEmail: 'SIGN IN WITH ',
    signInWithPhone: 'SIGN IN WITH YOUR ',
    mobile: ' MOBILE PHONE',
    email: ' EMAIL',
    contentPhone:
      'Enter a valid Mobile Number, and password then click continue and we will send you an SMS verification code.',
    contentEmail:
      ' Enter a valid email address, and password then click continue and we will send you an SMS verification code.',
    enterYourEmail: 'Enter your email',
    enterYourMobileNumber: 'Enter your Mobile Number',
    password: 'Password',
    forgotPassword: 'Forgot Password',
    continue: 'Continue',
    or: 'Or',
    signinMethod: 'Sign in with Google, Apple or Email',
    signinEmail: 'SignIn with Email',
    signinGoogle: 'SignIn with Google',
    signinApple: 'SignIn with Apple',
  },
  forgotPassword: {
    numberPlaceholder: 'Enter your mobile number',
    forgotPasswordHeader: 'Forgot Password',
    forgotPassword: 'FORGOT PASSWORD',
    content:
      'Enter a valid Email/Mobile Number, and password then click continue and we will send you an SMS verification code.',
    enterRegisteredNumber: 'Enter your registered Number',
    enterRegisteredEmail: 'Enter your registered Email',
    email: 'Enter Email',
    number: 'Enter Number',
    resetPassword: 'RESET PASSWORD',
  },
  resetPassword: {
    resetPassword: 'Reset Password',
    headerTitle: 'RESET PASSWORD',
    newPassword: 'NEW PASSWORD',
    confirmPassword: 'CONFIRM PASSWORD ',
    resetNow: 'RESET NOW ',
  },
  otpVerification: {
    otpVerification: 'Verification Code',
    verificationCode: 'VERIFICATION CODE',
    conent:
      'Enter the 4 digit SMS verification code for Reset Password that we have sent on your Email/Phone number',
    verifyNew: 'Verify now',
    resendIn: 'Resend in',
  },
  changesPassword: {
    changesPassword: 'Changes Password',
    oldPassword: 'Old Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm  Password',
    submit: 'Submit',
  },
  faxUpdatepopup: {
    faxDetails: 'Fax Details',
    priviewAttached: 'PREVIEW ATTACHED DOCUMENT/IMAGE',
    failed: 'FAILED',
  },
  faxCoverPage: {
    cancel: 'Cancel',
    recipient: 'Recipient',
    to: 'TO',
    recipientName: 'RECIPIENT NAME',
    Sender: 'SENDER',
    from: 'FROM',
    yourName: 'YOUR NAME',
    contact: 'CONTACT',
    yourPhone: 'YOUR PHONE OR EMAIL',
    subject: 'SUBJECT',
    faxAbout: 'WHAT IS THIS FAX ABOUT?',
    message: 'Message',
    wrightMassage: 'Write your message here',
    create: 'CREATE',
    faxCoverPage: 'Fax Cover Page',
  },
  preview: {
    preview: 'Preview',
    credits: ' Credits',
    sending: 'Sending a fax to:',
    page: ' Page ',
    machine:
      ' Fax may not be delivered if recipient’s line is busy or fax machine is off',
    send: 'Send Now',
    cancel: 'cancel',
    sendingFax: 'Sending....',
    hang: 'Hang tight, this may take a While',
    deliveryTime: 'Delivery Time',
    minutes: '3 Minutes',
  },
  FAQ: {
    appUsage: 'APP USAGE',
    faq: 'FAQ',
  },
  TermAndCondition: {
    termConditions: 'Term And Conditions',
  },
  privacyPolicy: {
    privacyPolicy: 'Privacy Policy',
  },
  eula: {
    eula: 'Eula',
  },
  aboutUs: {
    aboutUs: 'About Us',
  },
  tutorial: {
    tutorial: 'Tutorials',
  },
  notification: {
    notification: 'Notification',
    notificationHeader: 'Notification',
    pushNotifications: 'Push Notifications',
    getNotified: 'Get notified when you fax is sent.',
  },
  plan: {
    plane: 'Plane',
    choose: `Choose \nYour Plan`,
    unlimited: 'Unlimited \nfaxes',
    noAdd: 'Ad \nFree',
    tracking: 'Delivery \nNotification',
    enable: 'Enable Free Trial',
    continue: 'Continue',
    restor: 'Restor Purchase',
    save: 'SAVE',
    subscribe: 'Subscribe Annually \n',
    noPayment: 'No Payment Now',
    terms: 'Terms of Use',
    privacyPolicy: 'Privacy Policy',
    notes: 'Notes:',
    subscriptions: ' Subscriptions are auto-renewable in app- purchases.',
    enableFreeTrial: 'Free Trial Enabled ',
    dayFree: 'Get 3 Days Free',
    unlimitedFax: 'Unlimited faxes',
    then: `3-day free trial,\nthen $6.99/week`,
    month: `9.99/month`,
  },
  popup: {
    itsWay: 'Fax is on its way! 🚀 Check the History screen to see its Status.',
    faxDocument: 'What would you like to do with your fax document?',
    anotherNumber: 'Send to another number',
    deliveryReport: 'Open delivery report',
    shareFax: 'Share Fax',
    delete: 'Delete',
    cancel: 'CANCEL',
    sellSubscriptions: 'We sell subscriptions,\n',
    yourData: 'NOT YOUR DATA!',
    yourPrivacy: `SpeedyFAX App, your privacy and security are our top priority. You may have noticed that we DON'T require user login or request any personal information. ‘That's because we deeply respect your right to privacy.`,
    exclusively:
      ' We keep a minimal record of your fax data, exclusively for you to view your faxes in the history tab. You can erase this data at any time with a simple swipe. Once deleted, we hold no. further records.',
    contactSupport: 'Contact Support',
    gotIt: 'Got it!',
    haveQuestion: 'Have a question',
    faq: 'FAQ’s',
    howSecure: 'How secure is this app?',
    SigninMethod: 'SELECT SIGN IN METHOD',
    features: 'SIGN IN FOR MORE FEATURES',
    trouble: 'Having trouble in Sing in?',
    continue: 'CONTINUE',
    loginFirst: 'LOGIN FIRST',
    pleaseLogin: 'Please login to become a premium member!',
    reSend: 'Do you want to re-send ',
    failedFax: 'Failed fax',
    resend: 'RESEND',
    allSet: `YOU'RE ALL SET.`,
    purchase: 'Your Purchase was successful',
    ok: 'OK',
    feedBack: 'FEEDBACK',
    yourFax: 'Your Fax Was',
    delivered: `"Delivered Successfully”\n`,
    for: 'for',
    free: ` FREE.\n`,
    taking: '`Would you mind taking\n`',
    moment: 'a moment to',
    rate: ` rate this App\n`,
    spread: 'so we can spread the word?',
    rateSpeedyFax: 'Rate Speedy Fax App',
    remindLater: 'Remind me later',
    logout: 'Are you sure you want to logout of your Speedy Fax account',
    rateUs: 'Rate Us',
    pleaseRateUs: 'Please Rate Our Speedy Fax App on App store',
    signinApple: 'Signin With Apple',
    deleteAccount: 'Are you sure you want to delete your speedy fax account',
  },
};
